build: false
shallow_clone: true

environment:

  global:
    distutils_use_sdk: 1
    NOSE_COVER_PACKAGE: "ipykernel"

  matrix:
    - python: "C:/Python27-x64"
      sdkver: "v7.0"

    - python: "C:/Python27"
      sdkver: "v7.0"

    - python: "C:/Python34-x64"
      sdkver: "v7.1"

    - python: "C:/Python34"
      sdkver: "v7.1"

matrix:
  allow_failures:
  -  sdkver: "v7.0"

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

init:
  - ps: $Env:sdkbin = "C:\Program Files\Microsoft SDKs\Windows\" + $Env:sdkver + "\Bin"
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:sdkbin + ";" + $Env:path
install:
  # prepare pip
  - ps: python -m pip install --upgrade --no-binary wheel pip
  - ps: pip install --upgrade wheel
  - ps: pip --version
  # install package
  - ps: pip install -e .
  # install test requirements
  - ps: pip install nose nose-timer coverage mock nose_warnings_filters numpy matplotlib
  - ps: python -c 'import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)'
test_script:
  - nosetests -v --with-coverage --with-time ipykernel
