build: false
shallow_clone: true

environment:

  global:
    distutils_use_sdk: 1
    NOSE_COVER_PACKAGE: "ipykernel"

  matrix:
    - python: "C:/Python27-x64"
    - python: "C:/Python27"
    - python: "C:/Python34-x64"
    - python: "C:/Python34"
    - python: "C:/Python35-x64"
    - python: "C:/Python35"
    - python: "C:/Python36-x64"
    - python: "C:/Python36"

cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache

matix:
  fast_finish: True

init:
  - ps: $Env:path = $Env:python + ";" + $Env:python + "\scripts;" + $Env:path
install:
  # prepare pip
  - ps: python -m pip install --upgrade --no-binary wheel pip
  - ps: pip install --upgrade wheel
  - ps: pip --version
  # install package
  - ps: pip install -e .
  # install test requirements
  - cmd: pip install -r test-requirements.txt
  # show current setup
  - ps: pip freeze
  - ps: python -c 'import ipykernel.kernelspec; ipykernel.kernelspec.install(user=True)'
test_script:
  - nosetests -v --with-coverage --with-time ipykernel
